.code
	add r0, r21, r1
	mov (r31)(-8), r0
	subi r31, 8
	addi r0, 4095
	mov (r1)(-33), r4
	mov r0, (r1)(2047)
	mov r0, 177
	mov r0, (r31)(0)
	addi r31, 8
	priv r0, r1, r0, 3
	brr r31
	brr 920
	xor r0, r0, r0
	addi r0, 4095
	shftli r0, 12
	addi r0, 4095
	shftli r0, 12
	addi r0, 4095
	shftli r0, 12
	addi r0, 4095
	shftli r0, 12
	addi r0, 4095
	shftli r0, 4
	addi r0, 15
	priv r1, r0, r0, 4
	xor r0, r0, r0
	addi r0, 0
	shftli r0, 12
	addi r0, 0
	shftli r0, 12
	addi r0, 0
	shftli r0, 12
	addi r0, 0
	shftli r0, 12
	addi r0, 265
	shftli r0, 4
	addi r0, 12
.data
	322834289
.code
	brr 128
