.code
	add r0, r21, r1
	mov (r31)(-8), r0
	subi r31, 8
	addi r0, 4095
	mov r1, (r2)(0)
	mov r0, (r3)(-1)
	mov r15, (r8)(16)
	mov r4, (r7)(-2048)
	mov r1, (r2)(5)
	mov r1, r2
	mov r0, r0
	mov r7, r15
	mov r3, r4
	mov r1, 0
	mov r7, 2047
	mov r5, 16
	mov (r1)(0), r2
	mov (r3)(-4), r7
	mov (r15)(16), r0
	mov (r4)(-8), r6
	mov r0, (r31)(0)
	addi r31, 8
	priv r0, r1, r0, 3
	brr r31
	brr 920
	xor r0, r0, r0
	addi r0, 0
	shftli r0, 12
	addi r0, 167
	shftli r0, 12
	addi r0, 3162
	shftli r0, 12
	addi r0, 3143
	shftli r0, 12
	addi r0, 436
	shftli r0, 4
	addi r0, 7
	priv r1, r0, r0, 4
	xor r0, r0, r0
	addi r0, 0
	shftli r0, 12
	addi r0, 0
	shftli r0, 12
	addi r0, 0
	shftli r0, 12
	addi r0, 0
	shftli r0, 12
	addi r0, 269
	shftli r0, 4
	addi r0, 0
.data
	322834289
.code
	brr 128
