.code
	xor r6, r6, r6
	addi r6, 0
	shftli r6, 12
	addi r6, 0
	shftli r6, 12
	addi r6, 0
	shftli r6, 12
	addi r6, 0
	shftli r6, 12
	addi r6, 275
	shftli r6, 4
	addi r6, 4
	xor r7, r7, r7
	addi r7, 0
	shftli r7, 12
	addi r7, 0
	shftli r7, 12
	addi r7, 0
	shftli r7, 12
	addi r7, 0
	shftli r7, 12
	addi r7, 265
	shftli r7, 4
	addi r7, 4
	xor r8, r8, r8
	addi r8, 0
	shftli r8, 12
	addi r8, 0
	shftli r8, 12
	addi r8, 0
	shftli r8, 12
	addi r8, 0
	shftli r8, 12
	addi r8, 266
	shftli r8, 4
	addi r8, 12
	br r6
	mov r10, (r31)(0)
	xor r1, r1, r1
	addi r1, 1
	brgt r8, r10, r1
	mov r0, r10
	return	subi r31, 8
	mov (r31)(-8), r10
	subi r31, 8
	mov r1, r10
	subi r1, 1
	mov (r31)(-8), r1
	subi r31, 8
	call r7
	mov r1, (r31)(0)
	addi r31, 8
	mov r10, (r31)(0)
	addi r31, 8
	mov r11, r0
	addi r31, 8
	subi r31, 8
	mov (r31)(-8), r10
	subi r31, 8
	mov (r31)(-8), r11
	subi r31, 8
	mov r1, r10
	subi r1, 2
	mov (r31)(-8), r1
	subi r31, 8
	call r7
	mov r1, (r31)(0)
	addi r31, 8
	mov r11, (r31)(0)
	addi r31, 8
	mov r10, (r31)(0)
	addi r31, 8
	mov r12, r0
	addi r31, 8
	add r0, r11, r12
	return	xor r10, r10, r10
	xor r1, r1, r1
	priv r10, r1, r0, 3
	mov (r31)(-8), r10
	subi r31, 8
	call r7
	mov r10, (r31)(0)
	addi r31, 8
	xor r1, r1, r1
	mov r1, 1
	priv r1, r0, r0, 4
	priv r0, r0, r0, 0
