.code
	mov r1, 5
	xor r10, r10, r10
	addi r10, 0
	shftli r10, 12
	addi r10, 0
	shftli r10, 12
	addi r10, 0
	shftli r10, 12
	addi r10, 0
	shftli r10, 12
	addi r10, 260
	shftli r10, 4
	addi r10, 0
	call r10
	priv r1, r0, r0, 4
	priv r0, r0, r0, 0
	mov (r31)(-8), r2
	subi r31, 8
	mov (r31)(-8), r3
	subi r31, 8
	mov r3, 1
	mov r2, 1
	xor r11, r11, r11
	addi r11, 0
	shftli r11, 12
	addi r11, 0
	shftli r11, 12
	addi r11, 0
	shftli r11, 12
	addi r11, 0
	shftli r11, 12
	addi r11, 266
	shftli r11, 4
	addi r11, 4
	brgt r11, r1, r2
	mov r0, 1
	mov r3, (r31)(0)
	addi r31, 8
	mov r2, (r31)(0)
	addi r31, 8
	return	mul r3, r3, r1
	subi r1, 1
	mov r2, 1
	xor r11, r11, r11
	addi r11, 0
	shftli r11, 12
	addi r11, 0
	shftli r11, 12
	addi r11, 0
	shftli r11, 12
	addi r11, 0
	shftli r11, 12
	addi r11, 266
	shftli r11, 4
	addi r11, 4
	brgt r11, r1, r2
	mov r0, r3
	mov r3, (r31)(0)
	addi r31, 8
	mov r2, (r31)(0)
	addi r31, 8
	return